from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1302, 98)
        
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1301, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        
        self.Icon = QtWidgets.QLabel(self.frame)
        self.Icon.setGeometry(QtCore.QRect(30, 10, 80, 80))
        self.Icon.setFrameShape(QtWidgets.QFrame.Box)
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\download.png"))
        self.Icon.setScaledContents(True)
        self.Icon.setObjectName("Icon")
        
        self.TorrentNameLabel = QtWidgets.QLabel(self.frame)
        self.TorrentNameLabel.setGeometry(QtCore.QRect(138, 20, 280, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TorrentNameLabel.setFont(font)
        self.TorrentNameLabel.setObjectName("TorrentNameLabel")
        
        self.DownloadIcon = QtWidgets.QLabel(self.frame)
        self.DownloadIcon.setGeometry(QtCore.QRect(138, 50, 31, 31))
        self.DownloadIcon.setText("")
        self.DownloadIcon.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\cloud_download.png"))
        self.DownloadIcon.setScaledContents(True)
        self.DownloadIcon.setObjectName("DownloadIcon")
        
        self.CurrentDownloadLabel = QtWidgets.QLabel(self.frame)
        self.CurrentDownloadLabel.setGeometry(QtCore.QRect(175, 57, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.CurrentDownloadLabel.setFont(font)
        self.CurrentDownloadLabel.setObjectName("CurrentDownloadLabel")
        
        self.CurrentUpploadLabel = QtWidgets.QLabel(self.frame)
        self.CurrentUpploadLabel.setGeometry(QtCore.QRect(325, 57, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.CurrentUpploadLabel.setFont(font)
        self.CurrentUpploadLabel.setObjectName("CurrentUpploadLabel")
        
        self.UploadLabel = QtWidgets.QLabel(self.frame)
        self.UploadLabel.setGeometry(QtCore.QRect(290, 50, 31, 31))
        self.UploadLabel.setText("")
        self.UploadLabel.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\cloud_upload.png"))
        self.UploadLabel.setScaledContents(True)
        self.UploadLabel.setObjectName("UploadLabel")
        
        self.DownloadTimeLabel = QtWidgets.QLabel(self.frame)
        self.DownloadTimeLabel.setGeometry(QtCore.QRect(455, 57, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.DownloadTimeLabel.setFont(font)
        self.DownloadTimeLabel.setObjectName("DownloadTimeLabel")
        
        self.TimeIcon = QtWidgets.QLabel(self.frame)
        self.TimeIcon.setGeometry(QtCore.QRect(420, 50, 31, 31))
        self.TimeIcon.setText("")
        self.TimeIcon.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\time.png"))
        self.TimeIcon.setScaledContents(True)
        self.TimeIcon.setObjectName("TimeIcon")
        
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(140, 87, 825, 5))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        
        self.PercentageProgressBar = QtWidgets.QLabel(self.frame)
        self.PercentageProgressBar.setGeometry(QtCore.QRect(910, 68, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.PercentageProgressBar.setFont(font)
        self.PercentageProgressBar.setObjectName("PercentageProgressBar")
        
        self.InfoBTTN = QtWidgets.QPushButton(self.frame)
        self.InfoBTTN.setEnabled(True)
        self.InfoBTTN.setGeometry(QtCore.QRect(944, -10, 181, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.InfoBTTN.setFont(font)
        self.InfoBTTN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InfoBTTN.setAutoFillBackground(False)
        self.InfoBTTN.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InfoBTTN.setIcon(icon)
        self.InfoBTTN.setIconSize(QtCore.QSize(24, 24))
        self.InfoBTTN.setObjectName("InfoBTTN")
        
        self.PauseBTTN = QtWidgets.QPushButton(self.frame)
        self.PauseBTTN.setEnabled(True)
        self.PauseBTTN.setGeometry(QtCore.QRect(1120, -10, 181, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.PauseBTTN.setFont(font)
        self.PauseBTTN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PauseBTTN.setAutoFillBackground(False)
        self.PauseBTTN.setText("")
        icon1 = QtGui.QIcon()
        
        icon1.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\pause_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PauseBTTN.setIcon(icon1)
        self.PauseBTTN.setIconSize(QtCore.QSize(24, 24))
        self.PauseBTTN.setObjectName("PauseBTTN")
        
        self.InfoLabel = QtWidgets.QLabel(self.frame)
        self.InfoLabel.setGeometry(QtCore.QRect(1021, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setObjectName("InfoLabel")
        
        self.PauseLabel = QtWidgets.QLabel(self.frame)
        self.PauseLabel.setGeometry(QtCore.QRect(1193, 60, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.PauseLabel.setFont(font)
        self.PauseLabel.setObjectName("PauseLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TorrentNameLabel.setText(_translate("Form", "Torrent Ejemplo 14 1080p 4k"))
        self.CurrentDownloadLabel.setText(_translate("Form", "2,5 MB/S"))
        self.CurrentUpploadLabel.setText(_translate("Form", "2,5 MB/S"))
        self.DownloadTimeLabel.setText(_translate("Form", " 5 min 30 sec"))
        self.PercentageProgressBar.setText(_translate("Form", "25%"))
        self.InfoLabel.setText(_translate("Form", "INFO"))
        self.PauseLabel.setText(_translate("Form", "PAUSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
