import sys
sys.path.append(r'mgTorrent')
from Util.ViewFunctions import ViewFunctions as vf
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QDesktopWidget, QWidget
from Controller.MainWindowController import MainController as MC
from View.DownloadBar import Ui_Form as DownloadBar
class MainWindow(QMainWindow):
    def __init__(self, mainController):
        super().__init__()
        self.mainController = mainController
        self.mainController.set_main_view(self)
        self.initUi(self)
        self.setWindowTitle("mgTorrent")
        self.init_controller_connections()
        
    def initUi(self, MainWindow):
        self.setObjectName("MainWindow")
        self.resize(1440, 1024)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.DownloadsFrame = QtWidgets.QFrame(self.centralwidget)
        self.DownloadsFrame.setGeometry(QtCore.QRect(80, 540, 1351, 461))
        self.DownloadsFrame.setObjectName("DownloadsFrame")
        
        self.verticalLayoutWidget = QtWidgets.QWidget(self.DownloadsFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 19, 1291, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        
        self.DownloadsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.DownloadsLayout.setContentsMargins(0, 0, 0, 0)
        self.DownloadsLayout.setObjectName("DownloadsLayout")
        
        #Present Label when there ain't downloads Ready
        self.NoDownloadsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.NoDownloadsLabel.setFont(font)
        self.NoDownloadsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NoDownloadsLabel.setObjectName("NoDownloadsLabel")
        self.DownloadsLayout.addWidget(self.NoDownloadsLabel)
        
        # Side Bar and Buttons
        self.SideBar = QtWidgets.QFrame(self.centralwidget)
        self.SideBar.setGeometry(QtCore.QRect(-1, -1, 80, 1021))
        self.SideBar.setObjectName("SideBar")
        
        self.LogoutBTTN = QtWidgets.QPushButton(self.SideBar)
        self.LogoutBTTN.setGeometry(QtCore.QRect(25, 950, 31, 31))
        self.LogoutBTTN.setFlat(True)
        self.LogoutBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LogoutBTTN.setIcon(icon)
        self.LogoutBTTN.setIconSize(QtCore.QSize(35, 35))
        self.LogoutBTTN.setObjectName("LogoutBTTN")
        
        self.LogoutLABEL = QtWidgets.QLabel(self.SideBar)
        self.LogoutLABEL.setGeometry(QtCore.QRect(19, 985, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.LogoutLABEL.setFont(font)
        self.LogoutLABEL.setObjectName("LogoutLABEL")
        
        self.SettingsBTTN = QtWidgets.QPushButton(self.SideBar)
        self.SettingsBTTN.setGeometry(QtCore.QRect(25, 510, 31, 31))
        self.SettingsBTTN.setFlat(True)
        self.SettingsBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsBTTN.setIcon(icon1)
        self.SettingsBTTN.setIconSize(QtCore.QSize(35, 35))
        self.SettingsBTTN.setObjectName("SettingsBTTN")
        
        self.UploadsBTTN = QtWidgets.QPushButton(self.SideBar)
        self.UploadsBTTN.setGeometry(QtCore.QRect(25, 440, 31, 31))
        self.UploadsBTTN.setFlat(True)
        self.UploadsBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\cloud_upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadsBTTN.setIcon(icon2)
        self.UploadsBTTN.setIconSize(QtCore.QSize(35, 35))
        self.UploadsBTTN.setObjectName("UploadsBTTN")
        
        self.TorrentsBTTN = QtWidgets.QPushButton(self.SideBar)
        self.TorrentsBTTN.setGeometry(QtCore.QRect(25, 370, 31, 31))
        self.TorrentsBTTN.setFlat(True)
        self.TorrentsBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\hard_drive_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TorrentsBTTN.setIcon(icon3)
        self.TorrentsBTTN.setIconSize(QtCore.QSize(35, 35))
        self.TorrentsBTTN.setObjectName("TorrentsBTTN")
        
        self.DashboardBTTN = QtWidgets.QPushButton(self.SideBar)
        self.DashboardBTTN.setGeometry(QtCore.QRect(25, 300, 31, 31))
        self.DashboardBTTN.setFlat(True)
        self.DashboardBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardBTTN.setIcon(icon4)
        self.DashboardBTTN.setIconSize(QtCore.QSize(35, 35))
        self.DashboardBTTN.setObjectName("DashboardBTTN")
        
        self.DashboardLABEL = QtWidgets.QLabel(self.SideBar)
        self.DashboardLABEL.setGeometry(QtCore.QRect(8, 335, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.DashboardLABEL.setFont(font)
        self.DashboardLABEL.setObjectName("DashboardLABEL")
        
        self.TorrentsLABEL = QtWidgets.QLabel(self.SideBar)
        self.TorrentsLABEL.setGeometry(QtCore.QRect(13, 405, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.TorrentsLABEL.setFont(font)
        self.TorrentsLABEL.setObjectName("TorrentsLABEL")
        
        self.UploadLABEL = QtWidgets.QLabel(self.SideBar)
        self.UploadLABEL.setGeometry(QtCore.QRect(18, 475, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.UploadLABEL.setFont(font)
        self.UploadLABEL.setObjectName("UploadLABEL")
        
        self.SettingsLABEL = QtWidgets.QLabel(self.SideBar)
        self.SettingsLABEL.setGeometry(QtCore.QRect(15, 545, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.SettingsLABEL.setFont(font)
        self.SettingsLABEL.setObjectName("SettingsLABEL")
        
        # Top Bar with search bar and support Button
        self.TopBar = QtWidgets.QFrame(self.centralwidget)
        self.TopBar.setGeometry(QtCore.QRect(80, 0, 1351, 41))
        self.TopBar.setObjectName("TopBar")
        
        self.SearchBar = QtWidgets.QLineEdit(self.TopBar)
        self.SearchBar.setGeometry(QtCore.QRect(40, 10, 1000, 22))
        self.SearchBar.setToolTip("")
        self.SearchBar.setFrame(False)
        self.SearchBar.setObjectName("SearchBar")
        
        self.SearchIcon = QtWidgets.QLabel(self.TopBar)
        self.SearchIcon.setGeometry(QtCore.QRect(5, 5, 31, 31))
        self.SearchIcon.setText("")
        self.SearchIcon.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\search.png"))
        self.SearchIcon.setScaledContents(True)
        self.SearchIcon.setObjectName("SearchIcon")
        
        self.HelpSupport = QtWidgets.QLabel(self.TopBar)
        self.HelpSupport.setGeometry(QtCore.QRect(1209, 10, 121, 20))
        self.HelpSupport.setCursor(QtCore.Qt.PointingHandCursor)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.HelpSupport.setFont(font)
        self.HelpSupport.setObjectName("HelpSupport")
        
        self.HelpSupportIcon = QtWidgets.QLabel(self.TopBar)
        self.HelpSupportIcon.setGeometry(QtCore.QRect(1175, 5, 31, 31))
        self.HelpSupportIcon.setText("")
        self.HelpSupportIcon.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\support.png"))
        self.HelpSupportIcon.setScaledContents(True)
        self.HelpSupportIcon.setObjectName("HelpSupportIcon")
        
        self.BoxFrame = QtWidgets.QFrame(self.centralwidget)
        self.BoxFrame.setGeometry(QtCore.QRect(79, 39, 1351, 501))
        self.BoxFrame.setObjectName("BoxFrame")
        
        self.BytesUpBox = QtWidgets.QFrame(self.BoxFrame)
        self.BytesUpBox.setGeometry(QtCore.QRect(40, 50, 300, 300))
        self.BytesUpBox.setFrameShape(QtWidgets.QFrame.Box)
        self.BytesUpBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BytesUpBox.setObjectName("BytesUpBox")
        
        self.UploadLabel = QtWidgets.QLabel(self.BytesUpBox)
        self.UploadLabel.setGeometry(QtCore.QRect(20, 20, 77, 77))
        self.UploadLabel.setText("")
        self.UploadLabel.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\cloud_upload.png"))
        self.UploadLabel.setScaledContents(True)
        self.UploadLabel.setObjectName("UploadLabel")
        
        self.UploadSizeLabel = QtWidgets.QLabel(self.BytesUpBox)
        self.UploadSizeLabel.setGeometry(QtCore.QRect(30, 200, 169, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.UploadSizeLabel.setFont(font)
        self.UploadSizeLabel.setObjectName("UploadSizeLabel")
        
        self.UpLabel = QtWidgets.QLabel(self.BytesUpBox)
        self.UpLabel.setGeometry(QtCore.QRect(30, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UpLabel.setFont(font)
        self.UpLabel.setObjectName("UpLabel")
        
        self.BytesDownBox = QtWidgets.QFrame(self.BoxFrame)
        self.BytesDownBox.setGeometry(QtCore.QRect(360, 50, 300, 300))
        self.BytesDownBox.setFrameShape(QtWidgets.QFrame.Box)
        self.BytesDownBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BytesDownBox.setObjectName("BytesDownBox")
        
        self.DownloadIcon = QtWidgets.QLabel(self.BytesDownBox)
        self.DownloadIcon.setGeometry(QtCore.QRect(20, 20, 77, 77))
        self.DownloadIcon.setText("")
        self.DownloadIcon.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\cloud_download.png"))
        self.DownloadIcon.setScaledContents(True)
        self.DownloadIcon.setObjectName("DownloadIcon")
        
        self.DownloadSizeLabel = QtWidgets.QLabel(self.BytesDownBox)
        self.DownloadSizeLabel.setGeometry(QtCore.QRect(30, 200, 169, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.DownloadSizeLabel.setFont(font)
        self.DownloadSizeLabel.setObjectName("DownloadSizeLabel")
        
        self.DownLabel = QtWidgets.QLabel(self.BytesDownBox)
        self.DownLabel.setGeometry(QtCore.QRect(30, 240, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DownLabel.setFont(font)
        self.DownLabel.setObjectName("DownLabel")
        
        self.TotalDownBox = QtWidgets.QFrame(self.BoxFrame)
        self.TotalDownBox.setGeometry(QtCore.QRect(680, 50, 300, 300))
        self.TotalDownBox.setFrameShape(QtWidgets.QFrame.Box)
        self.TotalDownBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TotalDownBox.setObjectName("TotalDownBox")
        
        self.HardDriveLabel = QtWidgets.QLabel(self.TotalDownBox)
        self.HardDriveLabel.setGeometry(QtCore.QRect(20, 20, 77, 77))
        self.HardDriveLabel.setText("")
        self.HardDriveLabel.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\hard_drive_2.png"))
        self.HardDriveLabel.setScaledContents(True)
        self.HardDriveLabel.setObjectName("HardDriveLabel")
        
        self.TotalDownloadLabel = QtWidgets.QLabel(self.TotalDownBox)
        self.TotalDownloadLabel.setGeometry(QtCore.QRect(30, 200, 169, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.TotalDownloadLabel.setFont(font)
        self.TotalDownloadLabel.setObjectName("TotalDownloadLabel")
        
        self.TotalLabel = QtWidgets.QLabel(self.TotalDownBox)
        self.TotalLabel.setGeometry(QtCore.QRect(30, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TotalLabel.setFont(font)
        self.TotalLabel.setObjectName("TotalLabel")
        
        self.TorrentDownBox = QtWidgets.QFrame(self.BoxFrame)
        self.TorrentDownBox.setGeometry(QtCore.QRect(1000, 50, 300, 300))
        self.TorrentDownBox.setFrameShape(QtWidgets.QFrame.Box)
        self.TorrentDownBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TorrentDownBox.setObjectName("TorrentDownBox")
        
        self.TorrentLabel = QtWidgets.QLabel(self.TorrentDownBox)
        self.TorrentLabel.setGeometry(QtCore.QRect(110, 20, 77, 77))
        self.TorrentLabel.setText("")
        self.TorrentLabel.setPixmap(QtGui.QPixmap("mgTorrent\View\Material Icons\download.png"))
        self.TorrentLabel.setScaledContents(True)
        self.TorrentLabel.setObjectName("TorrentLabel")
        
        self.TorrentDownSizeLabel = QtWidgets.QLabel(self.TorrentDownBox)
        self.TorrentDownSizeLabel.setGeometry(QtCore.QRect(73, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.TorrentDownSizeLabel.setFont(font)
        self.TorrentDownSizeLabel.setObjectName("TorrentDownSizeLabel")
        
        self.TorrentDownHintLabel = QtWidgets.QLabel(self.TorrentDownBox)
        self.TorrentDownHintLabel.setGeometry(QtCore.QRect(60, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.TorrentDownHintLabel.setFont(font)
        self.TorrentDownHintLabel.setObjectName("TorrentDownHintLabel")
        
        self.TorrentDownORLabel = QtWidgets.QLabel(self.TorrentDownBox)
        self.TorrentDownORLabel.setGeometry(QtCore.QRect(135, 180, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TorrentDownORLabel.setFont(font)
        self.TorrentDownORLabel.setObjectName("TorrentDownORLabel")
        
        self.BrowseBTTN = QtWidgets.QPushButton(self.TorrentDownBox)
        self.BrowseBTTN.setGeometry(QtCore.QRect(45, 220, 210, 50))
        self.BrowseBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BrowseBTTN.setFont(font)
        self.BrowseBTTN.setObjectName("BrowseBTTN")
        
        self.RecentTorrents = QtWidgets.QLabel(self.centralwidget)
        self.RecentTorrents.setGeometry(QtCore.QRect(120, 515, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.RecentTorrents.setFont(font)
        self.RecentTorrents.setObjectName("RecentTorrents")
        
        self.SeeAllTorrentsBTTN = QtWidgets.QLabel(self.centralwidget)
        self.SeeAllTorrentsBTTN.setGeometry(QtCore.QRect(1300, 515, 111, 21))
        self.SeeAllTorrentsBTTN.setCursor(QtCore.Qt.PointingHandCursor)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SeeAllTorrentsBTTN.setFont(font)
        self.SeeAllTorrentsBTTN.setObjectName("SeeAllTorrentsBTTN")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NoDownloadsLabel.setText(_translate("MainWindow", "Looks like there is nothing here, Start Downloading!"))
        self.LogoutLABEL.setText(_translate("MainWindow", "LOGOUT"))
        self.DashboardLABEL.setText(_translate("MainWindow", "DASHBOARD"))
        self.TorrentsLABEL.setText(_translate("MainWindow", "TORRENTS"))
        self.UploadLABEL.setText(_translate("MainWindow", "UPLOAD"))
        self.SettingsLABEL.setText(_translate("MainWindow", "SETTINGS"))
        self.SearchBar.setPlaceholderText(_translate("MainWindow", " SEARCH FOR A TORRENT"))
        self.HelpSupport.setText(_translate("MainWindow", "HELP AND SUPPORT"))
        self.UploadSizeLabel.setText(_translate("MainWindow", "0 Gb"))
        self.UpLabel.setText(_translate("MainWindow", "Bytes Uploaded"))
        self.DownloadSizeLabel.setText(_translate("MainWindow", "0 Gb"))
        self.DownLabel.setText(_translate("MainWindow", "Bytes Downloaded"))
        self.TotalDownloadLabel.setText(_translate("MainWindow", "0 Gb"))
        self.TotalLabel.setText(_translate("MainWindow", "Total Downloaded on APP"))
        self.TorrentDownSizeLabel.setText(_translate("MainWindow", ".TORRENT, MAX SIZE 2MB"))
        self.TorrentDownHintLabel.setText(_translate("MainWindow", "Drag & Drop torrent files here"))
        self.TorrentDownORLabel.setText(_translate("MainWindow", "OR"))
        self.BrowseBTTN.setText(_translate("MainWindow", "Browse"))
        self.RecentTorrents.setText(_translate("MainWindow", "Recent Torrents"))
        self.SeeAllTorrentsBTTN.setText(_translate("MainWindow", "SEE ALL TORRENTS"))

        vf.load_stylesheet(self, "mgTorrent\View\Styles\Main.css")
        
    #This method connects the UI components to the controller methods.    
    def init_controller_connections(self):
        # Connecting sidebar buttons to controller methods
        self.LogoutBTTN.clicked.connect(self.mainController.logout)
        self.BrowseBTTN.clicked.connect(self.mainController.browse) 
    
    def hideLabels(self):
        self.NoDownloadsLabel.hide()    
        
    def center(self):
        qr = self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())    
        
if __name__ == "__main__":
    
    app = QApplication(sys.argv)
    download_controller = MC(DownloadBar)
    window = MainWindow(download_controller)
    window.show()
    window.center()
    sys.exit(app.exec_())